# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\x12\x07posebag\"\x90\x01\n\x08poseInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x12\n\n\x02qw\x18\x05 \x01(\x02\x12\n\n\x02qx\x18\x06 \x01(\x02\x12\n\n\x02qy\x18\x07 \x01(\x02\x12\n\n\x02qz\x18\x08 \x01(\x02\x12\x0c\n\x04\x63onf\x18\t \x01(\x02\x12\x12\n\nimage_data\x18\n \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSEINFO._serialized_start=24
  _POSEINFO._serialized_end=168
# @@protoc_insertion_point(module_scope)
